"""initial

Revision ID: 3c4fa86a9970
Revises: 
Create Date: 2022-11-16 15:55:24.525202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4fa86a9970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customer',
    sa.Column('customer_pk', sa.Integer(), nullable=False),
    sa.Column('customer_sk', sa.Integer(), nullable=False),
    sa.Column('customer_nk', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.String(length=5), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('changed_fields', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('customer_pk'),
    sa.UniqueConstraint('customer_sk', 'inserted_datetime', name='uk_dim_customer_id_ins'),
    sa.UniqueConstraint('customer_sk', 'updated_datetime', name='uk_dim_customer_id_upd'),
    sa.UniqueConstraint('email_address', 'inserted_datetime', name='uk_dim_customer_email_ins'),
    sa.UniqueConstraint('email_address', 'updated_datetime', name='uk_dim_customer_email_upd')
    )
    op.create_table('fact_daily_sales',
    sa.Column('sales_date', sa.Date(), nullable=False),
    sa.Column('customer_pk', sa.Integer(), nullable=False),
    sa.Column('customer_sk', sa.Integer(), nullable=False),
    sa.Column('sales_amount_eur', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('number_of_products', sa.Integer(), nullable=False),
    sa.Column('number_of_orders', sa.Integer(), nullable=False),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('sales_date', 'customer_pk', name='pk_fact_sales_cust_pk'),
    sa.UniqueConstraint('sales_date', 'customer_sk', name='uk_fact_sales_cust_sk')
    )
    op.create_table('raw_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_datetime', name='pk_raw_customer_id'),
    sa.UniqueConstraint('email_address', 'inserted_datetime', name='uk_raw_customer_email')
    )
    op.create_table('raw_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_status', sa.String(length=10), nullable=False),
    sa.Column('order_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_currency', sa.String(length=3), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('inserted_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'inserted_datetime', name='uk_raw_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_order')
    op.drop_table('raw_customer')
    op.drop_table('fact_daily_sales')
    op.drop_table('dim_customer')
    # ### end Alembic commands ###
