"""initial 2

Revision ID: aa3a8a88650a
Revises: 3c4fa86a9970
Create Date: 2022-11-16 16:15:37.694851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3a8a88650a'
down_revision = '3c4fa86a9970'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_customer', sa.Column('cut_off_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_customer', 'cut_off_date')
    # ### end Alembic commands ###
